### ISSUE TITLE
www.aros.org site down ?

### ISSUE THREAD

**Issue by mcarbonneaux** [aros-development-team/documentation#90]
the site [www.aros.org](http://www.aros.org/) seem to be down !?

what the problem ?

**Comment by mattrust** [comment]
I'm getting a SSL_ERROR_NO_CYPHER_OVERLAP error. I don't know how to solve that.

https://aros.sourceforge.io/ is working

**Comment by mcarbonneaux** [comment]
in http: you have this message:

![image](https://user-images.githubusercontent.com/8479023/192535569-5e9a7257-cf4d-4844-9300-a36184cf023d.png)
